name: build and publish RAPIDS manylinux

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker-manylinux:
    name: ${{ matrix.policy }} ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    strategy:
      matrix:
        include:
          - labels: [self-hosted, linux, amd64, cpu4]
            cpu-arch: x86_64
            policy: manylinux2014
            base-image: nvidia/cuda:11.5.1-devel-centos7

          - labels: [self-hosted, linux, amd64, cpu4]
            cpu-arch: x86_64
            policy: manylinux_2_31
            base-image: nvidia/cuda:11.5.1-devel-ubuntu20.04

          - labels: [self-hosted, linux, arm64, cpu4]
            cpu-arch: aarch64
            policy: manylinux2014
            base-image: nvidia/cuda:11.5.1-devel-centos7

          - labels: [self-hosted, linux, arm64, cpu4]
            cpu-arch: aarch64
            policy: manylinux_2_31
            base-image: nvidia/cuda:11.5.1-devel-ubuntu20.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: .buildx-cache-${{ matrix.policy }}_${{ matrix.cpu-arch }}/*
          key: buildx-cache-${{ matrix.policy }}-${{ matrix.cpu-arch }}-${{ hashFiles('docker/**') }}
          restore-keys: buildx-cache-${{ matrix.policy }}-${{ matrix.cpu-arch }}-
      - name: Build ${{ matrix.policy }} base container
        run: >
          COMMIT_SHA=latest
          POLICY=${{ matrix.policy }}
          PLATFORM=${{ matrix.cpu-arch }}
          BASEIMAGE_OVERRIDE="${{ matrix.base-image }}"
          ./build.sh
      - name: Re-tag as rapidsai/${{ matrix.policy }} containers
        run: docker tag quay.io/pypa/${{ matrix.policy }}_${{ matrix.cpu-arch }} rapidsai/${{ matrix.policy }}_${{ matrix.cpu-arch }}
      - name: Push rapidsai/manylinux containers to DockerHub
        if: ${{ inputs.push }}
        run: docker push rapidsai/${{ matrix.policy }}_${{ matrix.cpu-arch }}
